### ISSUE TITLE
[UX] Display heading checkboxes inline + less help text

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/permalink_filter#1]
Less scrolling -> better UX 🙂 

While at it, also changed the input labels, so that there is less help text in the form (where it made sense).

Before:

![Screen Shot 2019-08-19 at 9 54 09 pm](https://user-images.githubusercontent.com/2423362/63291667-ad697f80-c2cc-11e9-8368-2872407cb377.png)

After:

![Screen Shot 2019-08-19 at 10 02 28 pm](https://user-images.githubusercontent.com/2423362/63291856-10f3ad00-c2cd-11e9-9a8e-e2bbb2cbd04e.png)

**Comment by klonos** [comment]
PR: https://github.com/backdrop-contrib/permalink_filter/pull/2 😉

**Comment by ghost** [comment]
Committed most of your suggestions here: https://github.com/backdrop-contrib/permalink_filter/commit/897d517e74aefd38f6730c3e47f1e5a82e7f9563

If you're happy with that then feel free to close this issue.

**Comment by klonos** [comment]
Yup, looks fine 👍 

One minor comment: the reason why I had changed "before/after the tag" to "before/after each heading" was in order to a) clarify that **all headings** will be **automatically** converted to permalinks (using `each` instead of `the` - which could imply being able to select individual headings to be permalinked), and b) "tag" is a coder term; novice, non-coders understand "heading" better.

Just something to consider.

**Comment by ghost** [comment]
Hmm, the reason I used 'the' instead of 'each' was because you can choose which level headings/tags to add links to (so it's not necessarily all of them). And 'tag' instead of 'heading' because I'm thinking in future I could expand this to include other tags, not just headings...

**Comment by klonos** [comment]
Fair enough. Makes perfect sense then 👍
