### ISSUE TITLE
Idea: TOC block

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/permalink_filter#3]
Perhaps this module could provide a block, that could be placed in a sidebar region, which would pick the permalinks added, and use them to automatically generate a TOC.

**Comment by ghost** [comment]
I think maybe this'd be better as a separate module. Perhaps one of these would suffice and could be ported...? https://www.drupal.org/project/project_module?f[3]=drupal_core:103&f[4]=sm_field_project_type:full&text=Toc&solrsort=score+desc

**Comment by olafgrabienski** [comment]
Oh, there are *so many* TOC modules! On first sight (not tested), none of them looks really good to me. That said, a new one looks promising to me: https://www.drupal.org/project/tocbot

**Comment by olafgrabienski** [comment]
> That said, a new one looks promising to me: https://www.drupal.org/project/tocbot

... and some time later I ported Tocbot to Backdrop – actually a while ago but here's the link: https://backdropcms.org/project/tocbot
