### ISSUE TITLE
Settings changes not applied unless content is re-saved

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/permalink_filter#4]
I have created a piece of content with `h3`s, leaving the default settings. Everything worked like a charm OOTB 👍

...I then disabled the "H3" checkbox, and saved settings -> refreshed the page with the content that had `h3`s -> permalinks were still shown 👎 -> edit the content -> save w/o making any changes -> settings applied 👍 

...I then tried changing other settings, like the permalink text and position -> saved settings -> refreshed content page -> settings were not shown 👎 -> edited content and re-saved w/o changes -> settings applied 👍 

The only setting that seems to be applied instantly during my testing was the "Include default styling" ...when I disable that, and refresh the page, the permalinks are shown all the time (not only on hover). Reverting the setting, permalinks are once again shown only on hover, without having to edit and re-save the content.

**Comment by ghost** [comment]
The only thing I could think of was setting `'cache' => FALSE` in [hook_filter_info()](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.api.php/function/hook_filter_info/1), but that didn't work...

**Comment by ghost** [comment]
@klonos This should be fixed with https://github.com/backdrop-contrib/permalink_filter/commit/33262430ee6207d080f53715b7e5872aef05273d, can you confirm please?

**Comment by klonos** [comment]
Yup, fixed. Thanks 👍 

Did you find it required to use `$form['#submit'][] = 'permalink_filter_settings_form_submit';` for some reason? It is my understanding that `*_submit()` functions get called automagically. So if you have a `mymodule_whatever_form()` function, then if you add `mymodule_whatever_form_submit()` function, you don't need to specify a form `'#submit'`. Same thing with `*_validate()` functions I believe.

**Comment by klonos** [comment]
...I have actually tested the above by uncommenting that line, and things seem to work. So, curious why you had to specifically define '#submit'.

**Comment by klonos** [comment]
...yup, here you go: https://api.backdropcms.org/form_api#submit_property

> ... This is usually to add additional submit functions to a form, or to use an alternate function rather than the default form submission function which is the form ID with __submit_ appended to it.

**Comment by ghost** [comment]
I had the same thought, but when I tried without that line it didn't work... Might try again later.

Also, [system_settings_form()](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_settings_form/1) says:

> If you need to manipulate the data in a custom manner, you [can] put your own submission handler in the form array before calling this function

**Comment by klonos** [comment]
Cool. Either way, once you have done your own testing, and whether you end up keeping or removing that line, the problem is solved, so this issue here can be closed 😉 

Thanks once again 👍

**Comment by ghost** [comment]
Nope, doesn't work when removing call to custom submit function. I guess `system_settings_form()` is a special case...
